### ISSUE TITLE
UserRole Miss Moderator ？

### ISSUE THREAD

**Issue by farrywen** [jamesnetherton/zulip-java-client#266]
enum UserRole ：  Organization moderator: 300 is miss ？

**Comment by jamesnetherton** [comment]
Yes, well observed :eyes:. Thanks for reporting it.

No idea how I missed adding that :sweat_smile:. I proposed a fix in https://github.com/jamesnetherton/zulip-java-client/pull/267

I can try to cut a new 0.5.1 release tomorrow or later this week.

**Comment by jamesnetherton** [comment]
0.5.1 is now released and available in Maven Central.
