### ISSUE TITLE
the new features of zulip-java-client

### ISSUE THREAD

**Issue by youknowwjk** [jamesnetherton/zulip-java-client#269]
HI there，Can you release the new features of zulip-java-client as soon as possible? Because my project requires it, thank you.

**Comment by jamesnetherton** [comment]
I will try to release some time later today.

**Comment by jamesnetherton** [comment]
0.5.2 is now available in Maven Central:

https://github.com/jamesnetherton/zulip-java-client/releases/tag/0.5.2
