### ISSUE TITLE
Passing multiple narrows to captureMessageEvents causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Liucj123A** [jamesnetherton/zulip-java-client#372]
com.github.jamesnetherton.zulip.client.api.event.request.RegisterEventQueueApiRequest

`if (narrows.length > 0) {
    String[][] stringNarrows = new String[1][narrows.length];
    for (int i = 0; i < narrows.length; i++) {
        stringNarrows[i] = new String[] { narrows[i].getOperator(), narrows[i].getOperand() };
    }

    putParamAsJsonString(NARROW, stringNarrows);
}`

zh: 这个地方有一个小问题，也许是我配置错误导致的。但是我修改以后确实可以使用了
en: There is a small problem in this place, which may be caused by my misconfiguration. But I can actually use it after I modify it

zh: 在 `new String[1][narrows.length];` 这个位置似乎写反了。当我在下面代码中传递两个 narrow 时，这里会导致报错。我将错误信息放到了最后
en: In 'new String[1][narrows.length]; 'This position seems to be written upside down. When I pass two Narrows in the following code, this results in an error. I saved the error message for last

zh: 将代码更改为 `String[][] stringNarrows = new String[narrows.length][2];` 以后，我就没有报错了
en: Change the code to 'String[][] stringNarrows = new String[narrows.length][2]; 'Since then, I have made no mistakes

`
public RegisterEventQueueApiRequest(ZulipHttpClient client, Narrow... narrows) {
    super(client);
    putParamAsJsonString(EVENT_TYPES, MONITORED_EVENTS);

    if (narrows.length > 0) {
        String[][] stringNarrows = new String[narrows.length][2];
        for (int i = 0; i < narrows.length; i++) {
            stringNarrows[i] = new String[] { narrows[i].getOperator(), narrows[i].getOperand() };
        }

        putParamAsJsonString(NARROW, stringNarrows);
    }
}
`

`java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.github.jamesnetherton.zulip.client.api.event.request.RegisterEventQueueApiRequest.<init>(RegisterEventQueueApiRequest.java:38) ~[classes/:na]
	at com.github.jamesnetherton.zulip.client.api.event.EventPoller.start(EventPoller.java:78) ~[classes/:na]
	at com.example.chatboot.ZulipService.pollMessages(ZulipService.java:44) ~[classes/:na]
`

**Comment by jamesnetherton** [comment]
Thanks a lot for reporting this! It uncovered a few other issues with the events APIs which I have also fixed in #374.
