### ISSUE TITLE
Narrow operand does not support IntList as operand

### ISSUE THREAD

**Issue by drnetua** [jamesnetherton/zulip-java-client#389]
Problem addressed:
Fixing issue with getting dm messages by userId:
```java
        List<Message> dm = zulip.messages().getMessages(50, 50, Anchor.NEWEST)
                .withNarrows(Narrow.of("dm", "14"))
                .withAnchor(834373)
                .withGravatar(true)
                .execute();
```
will fail with:
```
com.github.jamesnetherton.zulip.client.exception.ZulipClientException: Invalid narrow operator: unknown user in 14
```                

Example call from web UI:

https://chat.foxminded.ua/json/messages?anchor=834373&num_before=50&num_after=50&narrow=%5B%7B%22negated%22%3Afalse%2C%22operator%22%3A%22dm%22%2C%22operand%22%3A%5B14%5D%7D%5D&client_gravatar=true

narrow here is:

```json
[
    {
        "negated": false,
        "operator": "dm",
        "operand": [14]
    }
]
```

fix in PR tested with 8.2 and successfully fetches messages as
```java
        List<Message> dm = zulip.messages().getMessages(50, 50, Anchor.NEWEST)
                .withNarrows(Narrow.of("dm", List.of(14)))
                .withAnchor(834373)
                .withGravatar(true)
                .execute();
```

**Comment by jamesnetherton** [comment]
Thanks for reporting this! I missed the note about it in the Zulip API docs.

> Prior to Zulip 8.0, the message ID operand for the id operator needed to be encoded as a string.

Not sure if you've tried, but you may be able to work around the issue by passing the raw String representation of the int array. E.g like `[1,2,3]`.

**Comment by drnetua** [comment]
@jamesnetherton I tried, but it will encode it as "[14]" and will give same error `Invalid narrow operator: unknown user in [14]`
